version: '3.7'

volumes:
  volume-mysql:
  volume-arcturus-maven-repo:
  volume-arcturus-target:
  volume-nitro-converter-node-modules:
  volume-nitro-react-node-modules:
  volume-orion-cms-vendor:

services:
  arcturus:
    container_name: arcturus
    build:
      context: emulator
    entrypoint: ["/bin/sh","/app/scripts/build.sh"]
    volumes:
      - ./emulator/:/app/
      - volume-arcturus-target:/app/arcturus/target
      - volume-arcturus-maven-repo:/root/.m2
    ports:
      - 3000:3000
      - 3001:3001
      - 2096:2096
    depends_on:
      - mysql
    networks:
      nitro:

  nitro:
    container_name: nitro
    build:
      context: nitro
    entrypoint: ["/bin/sh","/app/scripts/build.sh"]
    volumes:
      - ./nitro/:/app/
      - volume-nitro-converter-node-modules:/app/nitro-converter/node_modules
      - volume-nitro-react-node-modules:/app/nitro-react/node_modules
    ports:
      - 1080:5154
      - 1081:5155
      - 8080:8080
      - 8081:8081
    networks:
      nitro:

  php-fpm:
    container_name: php-fpm
    build:
      context: cms
    entrypoint: ["/bin/bash","/var/www/scripts/build.sh"]
    volumes:
      - ./cms/:/var/www/
      - volume-orion-cms-vendor:/app/orion-cms/vendor
    networks:
      nitro:

  nginx:
    image: nginx:latest
    volumes:
      - ./cms/:/var/www/
      - ./cms/configuration/nginx/orion.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 2080:80
    depends_on:
      - php-fpm
    links:
      - php-fpm
    networks:
      nitro:


  mysql:
    container_name: mysql
    image: mariadb:10.6
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=arcturus_root_pw
      - MYSQL_USER=arcturus_user
      - MYSQL_PASSWORD=arcturus_pw
      - MYSQL_DATABASE=arcturus
    volumes:
      - volume-mysql:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/dumps:/docker-entrypoint-initdb.d
    ports:
      - 13306:3306
    networks:
      nitro:

networks:
  nitro:
